//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatosWeb.Modelado
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MovimientoInventario
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "El campo ProductoId es obligatorio.")]
        public Nullable<int> ProductoId { get; set; }

        [Required(ErrorMessage = "El campo Descripción es obligatorio.")]
        [StringLength(100, ErrorMessage = "La Descripción no puede exceder los 100 caracteres.")]
        public string TipoMovimiento { get; set; }

        [Required(ErrorMessage = "El campo Cantidad es obligatorio.")]
        [Range(1, int.MaxValue, ErrorMessage = "La Cantidad debe ser al menos 1.")]
        public int Cantidad { get; set; }

        public Nullable<System.DateTime> FechaMovimiento { get; set; } = DateTime.Today;
    
        public virtual Producto Producto { get; set; }
    }
}
