//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatosWeb.Modelado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int Id { get; set; }
        public Nullable<int> FacturaVentaId { get; set; }
        public Nullable<decimal> MontoPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string MetodoPago { get; set; }
        public string EstadoPago { get; set; }
    
        public virtual FacturaVenta FacturaVenta { get; set; }
    }
}
