//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatosWeb.Modelado
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pago
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> FacturaVentaId { get; set; }
        public Nullable<decimal> MontoPago { get; set; }
<<<<<<< HEAD
        public Nullable<System.DateTime> FechaPago { get; set; } = DateTime.Now;
=======
        public Nullable<System.DateTime> FechaPago { get; set; }
>>>>>>> 74359c0d6097fad34d5222f0190d3674af346238
        public string MetodoPago { get; set; }
        public string EstadoPago { get; set; }
    
        public virtual FacturaVenta FacturaVenta { get; set; }
    }
}
